local monarch = require "monarch.monarch"

local oyster = require "oyster.oyster"
local gamestate = require "oyster.gamestate"
local playerdata = require "oyster.playerdata"
local stopwatch = require "oyster.stopwatch"

local rendercam = require "rendercam.rendercam"

function init(self)
	local states = {"TITLE","MAIN_MENU", "PAUSE", "LOADING", "MAP", "IN_GAME"}
	gamestate.init(states)
	gamestate.set("TITLE")
end
