function init(self)
	msg.post(".", "acquire_input_focus") 
	self.show_debug = false 
end

function on_input(self, action_id, action)
	if action_id == hash("click") and action.pressed then
		msg.post("@system:", "toggle_physics_debug") 
		if self.show_debug then 
			msg.post("main:/loader", "set_time_step", { factor = 1, mode = 0 })
		else
			msg.post("main:/loader", "set_time_step", { factor = 0.1, mode = 1 })
		end
		self.show_debug = not self.show_debug 
	end
end